version: 2.0
jobs: 
  build:
    docker:
     - image: denfenm/simple1.4:latest
    steps:
     - checkout
     - run:
          command: |
           python tests.py
     - persist_to_workspace:
          root: . #the folder to start the workspace from.
          paths: 
           - .        
  package:
    docker:
     - image: denfenm/simple1.4:latest
    steps:
     - attach_workspace:
          at: .  
     - run:
          command: |
           pip install -r requirements.txt
     - run:
          command: |
           python tests.py
     - persist_to_workspace:
          root: . #the folder to start the workspace from.
          paths: 
            - .
  zipping:
    docker:
     - image: denfenm/simple1.4:latest
    steps:
     - run:
        command: | 
           apt-get update -y
           apt-get install zip -y
           cd /ca-project
           mkdir artifact
           zip -r something.zip .
     - store_artifacts:
          path: /circleci/ca-project/artifact/something.zip
          destination: prefix
          

     
#update zip 
 
  dockerize:
    machine: true
    steps:
     #- checkout
      #Login to docker
     - docker login -u $DOCKER_USER -p $DOCKER_PASS
      #build the application image
     - run: docker build -t $DOCKER_USER/myapp:$CIRCLE_SHA1 .
      #deploy the image
     - run: docker push $DOCKER_USER/myapp:$CIRCLE_SHA1

workflows:
  version: 2
  myworkflows:
    jobs: 
     - build
     - package:
          requires:
           - build
     - zipping
     - dockerize:
          requires:
           - zipping

