version: 2.0
jobs: 
  build:
    docker:
     - image: denfenm/simple1.4:latest
    steps:
     - checkout
     - run:
          command: |
           python tests.py
     - persist_to_workspace:
          root: . #the folder to start the workspace from.
          paths: 
           - .        
  package:
    docker:
     - image: denfenm/simple1.4:latest
    steps:
     - attach_workspace:
          at: .  
     - run:
          command: |
           pip install -r requirements.txt
     - run:
          command: |
           python tests.py
     - persist_to_workspace:
          root: . #the folder to start the workspace from.
          paths: 
            - .
  zipping:
    docker:
     - image: denfenm/simple1.4:latest
    steps:
     - run:
        command: | 
           apt-get update -y
           apt-get install zip -y
           cd /ca-project
           mkdir artifact
           zip -r something.zip .
     - store_artifacts:
          path: /circleci/ca-project/artifact/something.zip
          destination: prefix
          
  update-repo:
    docker:
     - image: denfenm/simple1.4:latest
    steps:
     - run:
        command: 
           git fetch --prune
           git checkout master
           git pull origin master
           
  deploy:
    docker:
     - image: denfenm/simple1.4:latest
    steps:
     - attach_workspace:
          at: .
     - checkout
     - run:
          command: |
           git add .
           git commit -m "durudu"
           git push origin
     - persist_to_workspace:
          root: . #the folder to start the workspace from.
          paths: 
           - . 
     
#update zip 
 
  #dockerize:
   # machine: true 
    #- run:
    # name:Dockerizing setup
    # commands:
    #     docker
    #steps:
     #- checkout
     # Login to docker
     #- run: docker login -u $denfenm -p $Denfenm12
     # build the application image
     #- run: docker build -t $DOCKER_USER/myapp:$CIRCLE_SHA1 .
     # deploy the image
     #- run: docker push $DOCKER_USER/myapp:$CIRCLE_SHA1

workflows:
  version: 2
  myworkflows:
    jobs: 
     - build
     - package:
          requires:
           - build
     - zipping: 
          requires:
           - package
     - deploy:
          requires:
           - package
          filters:
           branches:
               only: master
