version: 2.0
jobs: 
  build:
    docker:
     - image: circleci/python:3.6
    steps:
     - checkout
     - run:
          command: |
           sudo pip install -r requirements.txt   
     - store_artifacts:
          path: ca-project/docker(1).zip
          destination: zip
     - store_test_results:
          path: build/test-results  
     - run:
          command: |
           python tests.py
     - persist_to_workspace:
          root: . #the folder to start the workspace from.
          paths: 
           - .        
  package:
    docker:
     - image: circleci/openjdk:8-jdk
    steps:
     - attach_workspace:
          at: .  
     - run:
          command: |
           pip install -r requirements.txt
     - store_artifacts:
          path: ca-project/docker(1).zip
          destination: zip
     - store_test_results:
          path: build/test-results
     - run:
          command: |
           python tests.py
     - persist_to_workspace:
          root: . #the folder to start the workspace from.
          paths: 
           - .
  dockerize:
    machine: true 
    #- run:
    # name:Dockerizing setup
    # commands:
    #     docker
    steps:
     - checkout
     # Login to docker
     - run: docker login -u $denfenm -p $Denfenm12
     # build the application image
     - run: docker build -t $DOCKER_USER/myapp:$CIRCLE_SHA1 .
     # deploy the image
     - run: docker push $DOCKER_USER/myapp:$CIRCLE_SHA1
