version: 2.0
jobs: 
  build:
    docker:
     - image: circleci/python:3.6
    steps:
     - checkout
     - run:
          command: |
           python pip install -r requirements.txt   
     - store_artifacts:
          path: build/libs
          destination: python_app
     - store_test_results:
          path: build/test-results  
     - run:
          command: |
           python tests.py
          
  package:
    docker:
     - image: circleci/openjdk:8-jdk
    steps:
     - attach_workspace:
          at: .  
     - run:
          command: |
           python pip install -r requirements.txt
     - store_artifacts:
          path: build/libs
          destination: python_app
     - store_test_results:
          path: build/test-results
     - run:
          command: |
           python tests.py

  dockerize:
    machine: true 
    #- run:
    # name:Dockerizing setup
    # commands:
    #     docker
    steps:
     - checkout
     # Login to docker
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
     # build the application image
     - run: docker build -t $DOCKER_USER/myapp:$CIRCLE_SHA1 .
     # deploy the image
     - run: docker push $DOCKER_USER/myapp:$CIRCLE_SHA1
